language: cpp

compiler:
  - gcc

before_script:
  - REPO_DIR=$PWD
  - mkdir -p tools && cd tools
  - wget -c "https://github.com/Kitware/CMake/archive/v3.4.1.tar.gz" -O CMake-3.4.1.tar.gz
  - tar -axvf CMake-3.4.1.tar.gz
  - CMAKE_PREFIX=$PWD/prebuilt/cmake
  - cd CMake-3.4.1
  - ./bootstrap --prefix=$CMAKE_PREFIX >> build_cmake.log 2>&1
  - make -j4 install >> build_cmake.log 2>&1
  - mkdir -p $REPO_DIR/build && cd $REPO_DIR/build
  - $CMAKE_PREFIX/bin/cmake ..

after_success:
  - test/coroutine_test
  
script: 
  - make -j4

install: true

branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

env:
  - LANG="zh_CN.UTF-8"

os:
  - linux
  - osx

osx_image: xcode61
