name: Build And Upload To coveralls.io
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build And Publish
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        shell: bash
        env:
          GCOV_FLAGS: "--coverage -fprofile-arcs -ftest-coverage"
        run: |
          mkdir -p "$GITHUB_WORKSPACE/build_jobs_dir_linux"
          cd "$GITHUB_WORKSPACE/build_jobs_dir_linux"
          cmake .. "-DCMAKE_C_FLAGS=$GCOV_FLAGS" "-DCMAKE_CXX_FLAGS=$GCOV_FLAGS" "-DCMAKE_EXE_LINKER_FLAGS=$GCOV_FLAGS" -DCMAKE_BUILD_TYPE=Debug -DLIBCOPP_FCONTEXT_USE_TSX=ON -DPROJECT_ENABLE_UNITTEST=ON -DPROJECT_ENABLE_SAMPLE=ON
          cmake --build . -j
      - name: Upload To coveralls.io
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE/build_jobs_dir_linux"
          cmake --build . -j -- run_sample run_test benchmark
          python3 -m pip install --user setuptools
          python3 -m pip install --user cpp-coveralls
          coveralls -r .. --gcov-options '\-lp' -e sample -e test -e build_jobs_dir_linux/CMakeFiles
